<a href="https://colab.research.google.com/github/Randi2512/jedi/blob/master/CART.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets

In [3]:
iris=datasets.load_iris()

In [5]:
print(iris.target_names)
print(iris.feature_names)


['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
data=iris.data
data.shape
#0-49 : setosa
#50-99 : versocolor
#100-149 : virginica

(150, 4)

In [13]:
fitur1=data[0:2,0]
fitur2=data[50:52,0]
fitur3=data[100:102,0]
fitur=np.concatenate((fitur1,fitur2,fitur3))
print(fitur)
target=np.array([0,0,1,1,2,2])
fitur=np.reshape(fitur,(-1,1))
print(fitur)

[5.1 4.9 7.  6.4 6.3 5.8]
[[5.1]
 [4.9]
 [7. ]
 [6.4]
 [6.3]
 [5.8]]


TRAINING

In [14]:
treeClf=DecisionTreeClassifier(max_depth=2)


In [17]:
treeClf.fit(fitur, target)

DecisionTreeClassifier(max_depth=2)

**TESTING**

In [26]:
print(treeClf.predict(fitur))

[0 0 1 1 2 2]


VISUAL **TREE** 

In [27]:
from sklearn.tree import export_graphviz


In [30]:
export_graphviz(treeClf, out_file='iris.dot', feature_names=iris.feature_names[0:1], class_names=iris.target_names)